/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AddAddress`; params?: Router.UnknownInputParams; } | { pathname: `/AddLocalization`; params?: Router.UnknownInputParams; } | { pathname: `/AddNomeCpf`; params?: Router.UnknownInputParams; } | { pathname: `/AvisosImportantes`; params?: Router.UnknownInputParams; } | { pathname: `/CadastroEmail`; params?: Router.UnknownInputParams; } | { pathname: `/DefinirSenha`; params?: Router.UnknownInputParams; } | { pathname: `/LoginEmail`; params?: Router.UnknownInputParams; } | { pathname: `/MarketplaceHome`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/ProductDetail`; params?: Router.UnknownInputParams; } | { pathname: `/SacolaTab`; params?: Router.UnknownInputParams; } | { pathname: `/TelaInicial`; params?: Router.UnknownInputParams; } | { pathname: `/ValidacaoEmail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AddAddress`; params?: Router.UnknownOutputParams; } | { pathname: `/AddLocalization`; params?: Router.UnknownOutputParams; } | { pathname: `/AddNomeCpf`; params?: Router.UnknownOutputParams; } | { pathname: `/AvisosImportantes`; params?: Router.UnknownOutputParams; } | { pathname: `/CadastroEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/DefinirSenha`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/MarketplaceHome`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/SacolaTab`; params?: Router.UnknownOutputParams; } | { pathname: `/TelaInicial`; params?: Router.UnknownOutputParams; } | { pathname: `/ValidacaoEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/AddAddress${`?${string}` | `#${string}` | ''}` | `/AddLocalization${`?${string}` | `#${string}` | ''}` | `/AddNomeCpf${`?${string}` | `#${string}` | ''}` | `/AvisosImportantes${`?${string}` | `#${string}` | ''}` | `/CadastroEmail${`?${string}` | `#${string}` | ''}` | `/DefinirSenha${`?${string}` | `#${string}` | ''}` | `/LoginEmail${`?${string}` | `#${string}` | ''}` | `/MarketplaceHome${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/ProductDetail${`?${string}` | `#${string}` | ''}` | `/SacolaTab${`?${string}` | `#${string}` | ''}` | `/TelaInicial${`?${string}` | `#${string}` | ''}` | `/ValidacaoEmail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AddAddress`; params?: Router.UnknownInputParams; } | { pathname: `/AddLocalization`; params?: Router.UnknownInputParams; } | { pathname: `/AddNomeCpf`; params?: Router.UnknownInputParams; } | { pathname: `/AvisosImportantes`; params?: Router.UnknownInputParams; } | { pathname: `/CadastroEmail`; params?: Router.UnknownInputParams; } | { pathname: `/DefinirSenha`; params?: Router.UnknownInputParams; } | { pathname: `/LoginEmail`; params?: Router.UnknownInputParams; } | { pathname: `/MarketplaceHome`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/ProductDetail`; params?: Router.UnknownInputParams; } | { pathname: `/SacolaTab`; params?: Router.UnknownInputParams; } | { pathname: `/TelaInicial`; params?: Router.UnknownInputParams; } | { pathname: `/ValidacaoEmail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
